### ISSUE TITLE
Add pdf output option 

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#44]
adding `format: pdf: default` to `_quarto.yml` resulted in pdf of only `index.qmd` on my first try. Cool that it adds "pdf" button to home page. 

Noting attempt here.

```
format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
  pdf: default    
```

![Screenshot 2024-06-15 at 3 42 45 PM](https://github.com/Openscapes/series/assets/11927811/908ac0a4-fa81-44db-8361-f33112fcd0c0)

## Output
hyperlinks worked, but links to `filename.qmd` were linked to that filename, not the html

![Screenshot 2024-06-15 at 4 04 30 PM](https://github.com/Openscapes/series/assets/11927811/20945efa-de4b-4a05-94b9-b96d3dc9034a)
